#!/bin/bash 


function update_host() {
  DOCKERID=$1
  DOCKERIP=`docker inspect $DOCKERID | grep IPAddress | cut -d '"' -f 4`
  HOSTNAME=`docker inspect $DOCKERID | grep \"Hostname\" | cut -d '"' -f 4`

  sed "s/[0-9\.]*\s$HOSTNAME/$DOCKERIP\t$HOSTNAME/g" /etc/hosts > /tmp/hosts
  mv /tmp/hosts /etc/hosts
}

for DOCKERID in `sudo docker ps | grep -v IMAGE | cut -f 1 -d " "`; do update_host $DOCKERID; done

# https://github.com/dotcloud/docker/issues/2335#issuecomment-30454483
sudo killall -HUP dnsmasq

grep amq /etc/hosts
